# Generated by Django 4.2.6 on 2023-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_alter_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(to='courses.tag'),
        ),
    ]
